### ISSUE TITLE
Url을 어떤 방식으로 작성해서 라우팅할지 의논해 봅시다.

### ISSUE THREAD

**Issue by cocoapi** [cocoapi/SE_webpage#12]
URL을 라우팅할때 페이지별 세부 URL을 어떻게 나누면 좋을지 의논해볼까합니다.

ex) 각 콘솔별 페이지는 www.pagename.com/[console_name]

각 URL별로 페이지가 다르게 출력되기 때문에 각 페이지는 최대한 명시적으로 하는것이 맞다고 생각합니다. 이에 대해 한번 의논해보는 시간을 가져볼까합니다.

**Comment by soondl** [comment]
세부 URL 이름은 자유롭게 정할 수 있나요?
예를들어 장바구니는 www.pagename.com/shopping_cart 이런 방식으로 가능한가요~❓

**Comment by cocoapi** [comment]
가능합니다. 페이지만들고 라우터에 추가만 해주면되는 정도라 ㅎ

**Comment by cocoapi** [comment]
또 어떤 URL이 추가로 필요할까요?

**Comment by cocoapi** [comment]
URL에 대한 라우팅은 완료되었으므로 이슈는 닫겠습니다.
